<?php

namespace Database\Seeders;

use App\Models\League;
use App\Models\Season;
use App\Models\SeasonTeam;
use App\Models\Team;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class BotTeamSeeder extends Seeder
{
    /**
     * Seed the bot teams used to fill league positions.
     */
    public function run(): void
    {
        $names = [
            'Wilda Brygada',
            'Jeżyce Squad',
            'Łazarz Legion',
            'Dębiec Crew',
            'Rataje Ultras',
            'Winogrady FC',
            'Piątkowo Fanatics',
            'Starołęka Force',
            'Grunwald Ekipa',
            'Chwaliszewo Hooligans',
            'Śródka Elite',
            'Garbary Front',
            'Ogrody Banda',
            'Sołacz Cartel',
            'Antoninek Vanguard',
            'Chartowo Power',
            'Naramowice Union',
            'Smochowice Guard',
            'Winiary Kings',
            'Główna Syndicate',
            'Podolany Alliance',
            'Strzeszyn Patrol',
            'Junikowo Division',
            'Górczyn Battalion',
            'Świerczewo Unit',
            'Spławie Troopers',
            'Minikowo Command',
            'Żegrze Overlords',
            'Kobylepole Rangers',
            'Morasko Titans',
            'Umultowo Knights',
            'Krzesiny Pilots',
            'Gniezno Królowie',
            'Kalisz Legion',
            'Konin Brygada',
            'Piła Ultras',
            'Ostrów Fanatics',
            'Leszno Squad',
            'Śrem Front',
            'Swarzędz Crew',
            'Luboń Force',
            'Września Elite',
            'Jarocin Punk',
            'Krotoszyn Cartel',
            'Turek Division',
            'Wągrowiec Vanguard',
            'Kościan Power',
            'Rawicz Guard',
            'Gostyń Syndicate',
            'Chodzież Unit',
            'Szamotuły Alliance',
            'Oborniki Kings',
            'Środa Overlords',
            'Pleszew Patrol',
            'Nowy Tomyśl',
            'Grodzisk Titans',
            'Wolsztyn Battalion',
            'Słupca Troopers',
            'Kępno Command',
            'Ostrzeszów Union',
            'Międzychód Knights',
            'Czarnków Rangers',
            'Złotów Army',
            'Trzcianka Force',
            'Kolejorz Spirit',
            'Parowóz Force',
            'Lokomotywa Ultras',
            'Pyra Power',
            'Koziołki Squad',
            'Niebiesko-Biali Elite',
            'Stary Dworzec',
            'Torowy Patrol',
            'Stalowy Bastion',
            'Parowy Walec',
            'Wielkopolski Herb',
            'Żelazna Gwardia',
            'Błękitna Fala',
            'Biały Groch',
            'Kocioł Power',
            'Bułgarska Crew',
            'Poznański Hufiec',
            'Para-Groch Squad',
            'Dymiąca Ekipa',
            'Żelazny Biskup',
            'Kozie Rogi',
            'Pyrowi Wojownicy',
            'Związkowy Front',
            'Pancerne Kozły',
            'Błękitny Pociąg',
            'Szynowy Cartel',
            'Express Kolejorz',
            'Tłoki Poznań',
            'Szybka Lokomotywa',
            'Złoty Kozioł',
            'Wąskotorowy Bunt',
            'Torowa Brygada',
            'Bździągwa Squad',
            'Szneka Team',
            'Gzuby Ultras',
            'Wypas Crew',
            'Bembel Power',
            'Wyrwiński Ekipa',
            'Kejter Force',
            'Bejm Elite',
            'Bimba Patrol',
            'Kaczor Cartel',
            'Fifny Squad',
            'Plyta Front',
            'Korbal Kings',
            'Strumyk Division',
            'Glapa Troopers',
            'Bambry Guard',
            'Chapa Band',
            'Kluka Unit',
            'Modrak Power',
            'Redyszkowy Bastion',
            'Tytka Army',
            'Rychloj Ekipa',
            'Fyrtel Kings',
            'Buchtowe Koziołki',
            'Szamot Ultras',
            'Rychły Front',
            'Ruchliwa Bimba',
            'Śliski Kejter',
            'Wielki Bembel',
            'Fifne Gzuby',
            'Złote Bejmy',
            'Stare Bambry',
            'Czarny Sztorm',
            'Niebieski Grom',
            'Stalowy Szpon',
            'Krwawy Bastion',
            'Cichy Sentinel',
            'Dziki Legion',
            'Mroczny Pakt',
            'Ostrzy Wojownicy',
            'Płonący Horyzont',
            'Żelazna Pięść',
            'Szybki Jastrząb',
            'Złoty Gryf',
            'Mroźny Wiatr',
            'Głęboki Cień',
            'Tytanowy Pancerz',
            'Wolni Strzelcy',
            'Gniewny Szron',
            'Nocny Patrol',
            'Błyskawica Cartel',
            'Szary Wilki',
            'Niszczyciele Grochu',
            'Burzowa Brygada',
            'Pancerne Skrzydła',
            'Ostry Kieł',
            'Srebrny Sztylet',
            'Pustynny Lew',
            'Żelazna Wola',
            'Mroźny Kieł',
            'Ostatni Bastion',
            'Wielki Pakt',
            'Niepowstrzymana Fala',
            'Czarna Gwardia',
            'Tajemnicze Pyry',
            'Kosmiczne Kozły',
            'Wściekłe Szneki',
            'Turbobimby Poznań',
            'Atomowe Gzuby',
            'Cyber Kolejorz',
            'Błyskawiczna Bździągwa',
            'Luksusowy Dębiec',
            'Galaktyczna Wilda',
            'Megawat Rataje',
            'Kwasowe Jeżyce',
            'Niewidzialny Łazarz',
            'Super Starołęka',
            'Laserowy Grunwald',
            'Niebezpieczna Śródka',
            'Eksplozywne Sołacz',
            'Pancerne Pyry',
            'Słoneczne Garbary',
            'Szalone Chwaliszewo',
            'Dymiąca Bimba',
            'Królewskie Ogrody',
            'Złote Winogrady',
            'Wybuchowe Piątkowo',
            'Żelazny Antoninek',
            'Groźne Chartowo',
            'Cyfrowe Naramowice',
            'Szybkie Smochowice',
            'Waleczne Winiary',
            'Ostre Podolany',
            'Kosmiczny Strzeszyn',
            'Mroczne Junikowo',
            'Super Górczyn',
            'Alpha Kolejorz',
            'Niebieska Armia',
            'Gamma Jeżyce',
            'Delta Łazarz',
            'Echo Dębiec',
            'Foxtrot Rataje',
            'Golf Winogrady',
            'Hotel Piątkowo',
            'India Starołęka',
            'Juliet Grunwald',
            'Kilo Swarzędz',
            'Lima Luboń',
            'Mike Gniezno',
            'November Kalisz',
            'Oscar Konin',
            'Pateraipanato Piła',
            'Quebec Ostrów',
            'Romeo Leszno',
            'Sierra Śrem',
            'Tango Września',
            'Uniform Jarocin',
            'Victor Krotoszyn',
            'Whiskey Turek',
            'Xray Kościan',
            'Yankee Gostyń',
            'Zulu Rawicz',
            'Apex Poznań',
            'Prime Kolejorz',
            'Ultra Pyra',
            'Mega Kozioł',
            'Legion Piła',
            'Tera Fyrtel',
            'Kolejorz Gaming',
            'Poznań Esports',
            'Wilda District',
            'Jeżyce Clan',
            'Rataje Nation',
            'Pyra Esports',
            'Bimba Tech',
            'Kozioł Prime',
            'Kocioł Crew',
            'Bułgarska Elite',
            'Warta Side',
            'Cytadela Squad',
            'Malta Force',
            'Sołacz Club',
            'Arena Poznań',
            'Kaponiera Team',
            'Teatralka Crew',
            'Bałtyk Squad',
            'Posnania Elite',
            'AWF Poznań',
            'Dworcowy Front',
            'Targi Squad',
            'MTP Force',
            'Lechia Poznań',
            'Warta Elite',
            'Olimpia Squad',
            'Poznamix Team',
            'Pyrlandia Squad',
            'Rogal Crew',
            'Gzuby Gaming',
            'Bamber Elite',
            'Fyrtel Squad',
        ];

        $botTeams = collect();

        foreach ($names as $index => $name) {
            $number = $index + 1;
            $user = User::query()->updateOrCreate(
                ['email' => sprintf('bot.%03d@lechtyper.local', $number)],
                [
                    'name' => $name,
                    'role' => 'user',
                    'password' => Hash::make('bot-'.$number),
                ],
            );

            $botTeams->push(Team::query()->updateOrCreate(
                ['user_id' => $user->id],
                ['name' => $name],
            ));
        }

        $season = Season::query()->where('status', 'active')->first();
        $backyardLeague = League::query()->where('level', 11)->first();
        $seasonLeague = $season?->seasonLeagues()->where('league_id', $backyardLeague?->id)->first();

        if ($seasonLeague !== null) {
            foreach ($botTeams as $botTeam) {
                SeasonTeam::query()->firstOrCreate([
                    'season_league_id' => $seasonLeague->id,
                    'team_id' => $botTeam->id,
                ]);
            }
        }
    }
}
