<!DOCTYPE html>
<html lang="pl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ config('app.name') }} | Zarządzanie ligą</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body><div class="admin-shell"><div class="container-fluid"><div class="row min-vh-100">
@include('admin.partials.sidebar')
<main class="admin-content col-lg-10 p-3 p-md-4 p-xl-5">
<header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><p class="eyebrow mb-2">Rozgrywki</p><h1 class="font-display h3 mb-1">Zarządzanie ligami</h1><p class="text-muted-custom mb-0">Zarządzaj drużynami kiboli i ich parami.</p></div><form method="POST" action="{{ route('logout') }}" class="m-0">@csrf<button class="btn btn-outline-secondary">Wyloguj</button></form></header>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="bg-white border rounded-3 p-3 p-md-4 mb-4"><form method="GET" action="{{ route('admin.leagues.index') }}" class="row g-3 align-items-end"><div class="col-md-5"><label class="form-label">Sezon</label><select class="form-select" name="season_id" onchange="this.form.submit()">@foreach($seasons as $availableSeason)<option value="{{ $availableSeason->id }}" @selected($availableSeason->id === $season->id)>{{ $availableSeason->name }} ({{ $availableSeason->status }})</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Liga</label><select class="form-select" name="league" onchange="this.form.submit()">@foreach($seasonLeagues as $availableSeasonLeague)<option value="{{ $availableSeasonLeague->league->slug }}" @selected($availableSeasonLeague->id === $selectedSeasonLeague->id)>{{ $availableSeasonLeague->league->name }}</option>@endforeach</select></div></form></section>
<div class="row g-4"><section class="col-xl-8">
<div class="bg-white border rounded-3 p-4 mb-4"><div class="d-flex justify-content-between align-items-start mb-3"><div><p class="eyebrow mb-2">{{ $season->name }}</p><h2 class="font-display h4 mb-1">{{ $selectedSeasonLeague->league->name }}</h2><p class="text-muted-custom mb-0">Pozycje: {{ $positions->whereNotNull('team_id')->count() }} / 10 obsadzonych · {{ $selectedMatches->count() }} meczów</p></div><span class="badge text-bg-light">Boty uzupełniają puste miejsca</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>Drużyna</th><th>Właściciel</th></tr></thead><tbody>@foreach($positions as $position)<tr><td>{{ $position->position }}</td><td><strong>{{ $position->displayName() }}</strong>@if($position->team && str_starts_with(strtolower((string) ($position->team->user?->email ?? '')), 'bot.'))<span class="ms-2" title="Bot">🤖</span>@endif</td><td>{{ $position->team?->user?->name ?? 'System' }}</td></tr>@endforeach</tbody></table></div></div>
<div class="bg-white border rounded-3 p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><p class="eyebrow mb-2">Terminarz ligi</p><h2 class="font-display h5 mb-0">Mecze drużyn kiboli</h2></div><span class="badge text-bg-light">{{ $selectedMatches->count() }} / 45</span></div><div class="d-grid gap-3">@forelse($selectedRounds as $round)<div class="border rounded-3 p-3"><div class="d-flex justify-content-between mb-2"><strong>Kolejka {{ $round->round_number }}</strong><span class="small text-muted-custom">{{ $round->matches->count() }} meczów @if($round->real_score_home !== null) · rozliczona @endif</span></div><div class="d-grid gap-1 mb-3">@forelse($round->matches as $match)<div class="small">{{ $match->homeTeam->name }} - {{ $match->awayTeam->name }}@if($match->status === 'completed')<strong class="ms-2">{{ $match->home_score }}:{{ $match->away_score }}</strong>@endif</div>@empty<p class="small text-muted-custom mb-0">Brak wygenerowanych par.</p>@endforelse</div>
<form method="POST" action="{{ route('admin.leagues.rounds.update', $round) }}" class="border-top pt-3">@csrf @method('PUT')<input type="hidden" name="scheduled_at" value="{{ $round->scheduled_at->format('Y-m-d\TH:i') }}"><div class="row g-2 mb-2"><div class="col-md-4"><input class="form-control form-control-sm" name="real_home_team" value="{{ $round->real_home_team }}" placeholder="Gospodarz" required></div><div class="col-md-4"><input class="form-control form-control-sm" name="real_away_team" value="{{ $round->real_away_team }}" placeholder="Gość" required></div><div class="col-md-4"><select class="form-select form-select-sm" name="competition" required><option value="">Rozgrywki</option>@foreach(\App\Http\Controllers\AdminLeagueManagementController::COMPETITIONS as $competition)<option value="{{ $competition }}" @selected($round->competition === $competition)>{{ $competition }}</option>@endforeach</select></div></div><div class="row g-2 mb-2"><div class="col-md-3"><input class="form-control form-control-sm" type="number" min="0" max="99" name="real_score_home" value="{{ $round->real_score_home }}" placeholder="Wynik gospodarza"></div><div class="col-md-3"><input class="form-control form-control-sm" type="number" min="0" max="99" name="real_score_away" value="{{ $round->real_score_away }}" placeholder="Wynik gościa"></div></div>@if($round->bonusQuestions->isNotEmpty())<div class="row g-2 mb-2">@foreach($round->bonusQuestions as $question)<div class="col-md-6"><label class="form-label small mb-1">{{ $question->type === 'offensive' ? 'Ofensywne' : 'Defensywne' }}: {{ $question->question_text }}</label><select class="form-select form-select-sm" name="correct_answers[{{ $question->id }}]"><option value="">Brak</option><option value="1" @selected($question->correct_answer === true)>TAK</option><option value="0" @selected($question->correct_answer === false)>NIE</option></select></div>@endforeach</div>@endif<button class="btn btn-outline-primary btn-sm">Zapisz i rozlicz kolejkę</button></form>
</div>@empty<p class="text-muted-custom mb-0">Brak wygenerowanych kolejek.</p>@endforelse</div></div>
</section><aside class="col-xl-4">
<div class="bg-white border rounded-3 p-4 mb-4"><p class="eyebrow mb-2">Uczestnicy</p><h3 class="font-display h5 mb-3">Dodaj drużynę na pozycję</h3><p class="text-muted-custom small">Dla 10 drużyn powstanie 45 unikalnych meczów. Puste pozycje grają jako Chłopaki z orlika.</p><form method="POST" action="{{ route('admin.leagues.teams.store') }}">@csrf<input type="hidden" name="season_league_id" value="{{ $selectedSeasonLeague->id }}"><select class="form-select mb-2" name="user_id" required><option value="">Wybierz użytkownika</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} - {{ $user->email }}</option>@endforeach</select><select class="form-select mb-3" name="position" required><option value="">Wybierz pozycję</option>@foreach($positions as $position)@php $isBotPosition = $position->team && $position->team->user && (str_starts_with(strtolower((string) $position->team->user->email), 'bot.') || str_contains(strtolower((string) $position->team->user->email), 'bot.')); @endphp<option value="{{ $position->position }}" @disabled($position->team_id !== null && ! $isBotPosition)>{{ $position->position }}{{ $isBotPosition ? ' - bot / do zastąpienia' : ($position->team ? ' - zajęta' : ' - wolna') }}</option>@endforeach</select><button class="btn btn-primary">Dodaj drużynę</button></form></div>
<div class="bg-white border rounded-3 p-4 mb-4"><p class="eyebrow mb-2">Generowanie par</p><h3 class="font-display h5 mb-2">Automatyczny terminarz</h3><p class="text-muted-custom small">Pary tworzą się automatycznie po utworzeniu sezonu. W lidze z 10 pozycjami powstaje 9 kolejek i 45 meczów.</p></div>
<div class="bg-white border rounded-3 p-4"><p class="eyebrow mb-2">Zasady ligi</p><h3 class="font-display h5 mb-3">Awans i spadek</h3><form method="POST" action="{{ route('admin.leagues.seasons.update', $selectedSeasonLeague) }}">@csrf @method('PUT')<label class="form-label">Miejsca awansu</label><input class="form-control mb-3" type="number" min="0" name="promotion_places" value="{{ $selectedSeasonLeague->promotion_places }}" required><label class="form-label">Miejsca spadku</label><input class="form-control mb-3" type="number" min="0" name="relegation_places" value="{{ $selectedSeasonLeague->relegation_places }}" required><button class="btn btn-primary">Zapisz zasady</button></form></div>
</aside></div></main></div></div></div></body></html>
