<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name') }} | Zarządzanie ligą</title>
    <link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
<div class="admin-shell"><div class="container-fluid"><div class="row min-vh-100">
    @include('admin.partials.sidebar')
    <main class="admin-content col-lg-10 p-3 p-md-4 p-xl-5">
        <header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4">
            <div><p class="eyebrow mb-2">Rozgrywki</p><h1 class="font-display h3 mb-1">Zarządzanie ligami</h1><p class="text-muted-custom mb-0">Wybierz sezon i jedną ligę, aby zarządzać jej szczegółami.</p></div>
            <form method="POST" action="{{ route('logout') }}" class="m-0">@csrf<button class="btn btn-outline-secondary">Wyloguj</button></form>
        </header>
        @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        <section class="bg-white border rounded-3 p-3 p-md-4 mb-4"><form method="GET" action="{{ route('admin.leagues.index') }}" class="row g-3 align-items-end">
            <div class="col-md-5"><label class="form-label">Sezon</label><select class="form-select" name="season_id" onchange="this.form.submit()">@foreach($seasons as $availableSeason)<option value="{{ $availableSeason->id }}" @selected($availableSeason->id === $season->id)>{{ $availableSeason->name }} ({{ $availableSeason->status }})</option>@endforeach</select></div>
            <div class="col-md-5"><label class="form-label">Liga</label><select class="form-select" name="league" onchange="this.form.submit()">@foreach($seasonLeagues as $availableSeasonLeague)<option value="{{ $availableSeasonLeague->league->slug }}" @selected($availableSeasonLeague->id === $selectedSeasonLeague->id)>{{ $availableSeasonLeague->league->name }} - poziom {{ $availableSeasonLeague->league->level }}</option>@endforeach</select></div>
            <div class="col-md-2"><span class="badge text-bg-primary">{{ $selectedSeasonLeague->league->name }}</span></div>
        </form></section>

        <div class="row g-4"><section class="col-xl-8">
            <div class="bg-white border rounded-3 p-4 mb-4"><div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><p class="eyebrow mb-2">{{ $season->name }}</p><h2 class="font-display h4 mb-1">{{ $selectedSeasonLeague->league->name }}</h2><p class="text-muted-custom mb-0">Poziom {{ $selectedSeasonLeague->league->level }} - {{ $selectedTeams->count() }} druzyn</p></div><span class="badge {{ $selectedSeasonLeague->league->is_swiss ? 'text-bg-warning' : 'text-bg-light' }}">{{ $selectedSeasonLeague->league->is_swiss ? 'System szwajcarski' : 'Liga klasyczna' }}</span></div><h3 class="font-display h6 mb-3">Sklad ligi</h3><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>Druzyna</th><th>Uzytkownik</th><th>Punkty</th><th>Aktywnosc</th><th>Akcje</th></tr></thead><tbody>@forelse($selectedTeams->sortBy(fn ($item) => $item->position ?? 999) as $seasonTeam)@php($submittedType = $seasonTeam->hasSubmittedTypeInSeason())<tr><td>{{ $seasonTeam->position ?? $loop->iteration }}</td><td><strong>{{ $seasonTeam->team->name }}</strong></td><td>{{ $seasonTeam->team->user->name }}</td><td>{{ $seasonTeam->points }}</td><td><span class="badge {{ $submittedType ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $submittedType ? 'Typowala' : 'Brak typow' }}</span></td><td><form method="POST" action="{{ route('admin.leagues.teams.destroy', $seasonTeam) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Usun</button></form></td></tr>@empty<tr><td colspan="6" class="text-muted-custom">Brak druzyn w tej lidze.</td></tr>@endforelse</tbody></table></div></div>

            <div class="bg-white border rounded-3 p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><p class="eyebrow mb-2">Terminarz</p><h3 class="font-display h5 mb-0">Kolejki {{ $selectedSeasonLeague->league->name }}</h3></div><span class="badge text-bg-light">{{ $selectedRounds->count() }} kolejek</span></div><div class="d-grid gap-3">@forelse($selectedRounds as $round)<div class="border rounded-3 p-3"><div class="d-flex justify-content-between align-items-center mb-3"><strong>Kolejka {{ $round->round_number }}</strong><span class="small text-muted-custom">{{ $round->scheduled_at->format('d.m.Y H:i') }}</span></div><form method="POST" action="{{ route('admin.leagues.rounds.update', $round) }}">@csrf @method('PUT')<div class="row g-2"><div class="col-md-6"><label class="form-label small">Mecz Lecha - data</label><input class="form-control" type="datetime-local" name="real_match_at" value="{{ $round->real_match_at?->format('Y-m-d\\TH:i') }}"></div><div class="col-md-6"><label class="form-label small">Rozgrywki</label><input class="form-control" name="competition" value="{{ $round->competition }}" placeholder="PKO Ekstraklasa" required></div><div class="col-md-6"><label class="form-label small">Gospodarz</label><input class="form-control" name="real_home_team" value="{{ $round->real_home_team }}" placeholder="Lech Poznan" required></div><div class="col-md-6"><label class="form-label small">Gosc</label><input class="form-control" name="real_away_team" value="{{ $round->real_away_team }}" placeholder="Rywal" required></div><div class="col-12"><button class="btn btn-outline-primary btn-sm">Zapisz mecz Lecha</button></div></div></form>@if($round->matches->isNotEmpty())<div class="small text-muted-custom mt-3">Mecze typowania: @foreach($round->matches as $match){{ $match->homeTeam->name }} vs {{ $match->awayTeam->name }}@if(!$loop->last), @endif @endforeach</div>@endif</div>@empty<p class="text-muted-custom mb-0">Kolejki nie zostaly jeszcze wygenerowane.</p>@endforelse</div></div>
        </section>

        <aside class="col-xl-4"><div class="bg-white border rounded-3 p-4 mb-4"><p class="eyebrow mb-2">Zasady ligi</p><h3 class="font-display h5 mb-3">Awans i spadek</h3><form method="POST" action="{{ route('admin.leagues.seasons.update', $selectedSeasonLeague) }}">@csrf @method('PUT')<label class="form-label">Miejsca awansu</label><input class="form-control mb-3" type="number" min="0" name="promotion_places" value="{{ $selectedSeasonLeague->promotion_places }}" required><label class="form-label">Miejsca spadku</label><input class="form-control mb-3" type="number" min="0" name="relegation_places" value="{{ $selectedSeasonLeague->relegation_places }}" required><button class="btn btn-primary">Zapisz zasady</button></form></div>

        <div class="bg-white border rounded-3 p-4 mb-4"><p class="eyebrow mb-2">Nowy sezon</p><h3 class="font-display h5 mb-3">Utworz sezon</h3><p class="text-muted-custom small">Druzyny ligi podworkowej bez zadnego typu w zakonczonym sezonie zostana usuniete razem z kontami. Aktywne druzyny zostana przepisane.</p><form method="POST" action="{{ route('admin.leagues.seasons.create') }}">@csrf<div class="mb-2"><label class="form-label">Nazwa sezonu</label><input class="form-control" name="name" required></div><div class="row g-2 mb-2"><div class="col-6"><label class="form-label">Start</label><input class="form-control" type="date" name="starts_at" required></div><div class="col-6"><label class="form-label">Koniec</label><input class="form-control" type="date" name="ends_at" required></div></div><div class="mb-3"><label class="form-label">Liczba kolejek</label><input class="form-control" type="number" min="1" max="255" name="rounds" value="9" required></div><button class="btn btn-primary">Utworz sezon</button></form></div>

        <div class="bg-white border rounded-3 p-4"><p class="eyebrow mb-2">Terminarz par</p><h3 class="font-display h5 mb-2">Generuj 9 kolejek</h3><p class="text-muted-custom small">Pary zostaną wygenerowane automatycznie bez podawania dat. Datę konkretnego meczu Lecha przypiszesz później w zakładce Terminarz.</p>@if($selectedRounds->isEmpty())<form method="POST" action="{{ route('admin.leagues.schedule.generate') }}">@csrf<input type="hidden" name="season_league_id" value="{{ $selectedSeasonLeague->id }}"><button class="btn btn-primary mt-2">Generuj pary</button></form>@else<p class="text-muted-custom small mb-0">Pary zostały już wygenerowane.</p>@endif</div></aside></div>
    </main>
</div></div></div>
</body>
</html>
