<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name') }} | Terminarz</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
<div class="admin-shell"><div class="container-fluid"><div class="row min-vh-100">
    @include('admin.partials.sidebar')
    <main class="admin-content col-lg-10 p-3 p-md-4 p-xl-5">
        <header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><p class="eyebrow mb-2">Rozgrywki</p><h1 class="font-display h3 mb-1">Terminarz</h1><p class="text-muted-custom mb-0">Dodaj rzeczywiste mecze Lecha i przypisz je do kolejek sezonu.</p></div><form method="POST" action="{{ route('logout') }}" class="m-0">@csrf<button class="btn btn-outline-secondary">Wyloguj</button></form></header>
        @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <section class="bg-white border rounded-3 p-3 p-md-4 mb-4"><form method="GET" action="{{ route('admin.schedule.index') }}"><label class="form-label">Sezon</label><select class="form-select" name="season_id" onchange="this.form.submit()">@foreach($seasons as $availableSeason)<option value="{{ $availableSeason->id }}" @selected($availableSeason->id === $season->id)>{{ $availableSeason->name }} ({{ $availableSeason->status }})</option>@endforeach</select></form></section>
        <section class="bg-white border rounded-3 p-4 mb-4"><p class="eyebrow mb-2">Nowy mecz Lecha</p><h2 class="font-display h5 mb-3">Dodaj źródło wyników</h2><form method="POST" action="{{ route('admin.schedule.matches.store') }}"><div class="row g-3">@csrf<input type="hidden" name="season_id" value="{{ $season->id }}"><div class="col-md-6"><label class="form-label">Data i godzina</label><input class="form-control" type="datetime-local" name="scheduled_at" required></div><div class="col-md-6"><label class="form-label">Rozgrywki</label><select class="form-select" name="competition" required><option value="">Wybierz rozgrywki</option>@foreach(['Ekstraklasa', 'Puchar Polski', 'Mecz towarzyski', 'Liga Mistrzów', 'Liga Europy', 'Liga Konferencji'] as $competition)<option value="{{ $competition }}">{{ $competition }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Gospodarz</label><input class="form-control" name="home_team" value="Crystal Palace" required></div><div class="col-md-6"><label class="form-label">Gość</label><input class="form-control" name="away_team" value="Lech Poznań" required></div><div class="col-md-6"><label class="form-label">Kolejka</label><select class="form-select" name="season_round_id"><option value="">Przypisz później</option>@foreach($rounds as $round)<option value="{{ $round->id }}" @disabled($round->realMatch !== null)>Kolejka {{ $round->round_number }}{{ $round->realMatch ? ' - zajęta' : '' }}</option>@endforeach</select></div><div class="col-12"><button class="btn btn-primary">Dodaj mecz</button></div></div></form></section>
        <section class="bg-white border rounded-3 p-4 mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><p class="eyebrow mb-2">Typer Lecha</p><h2 class="font-display h5 mb-0">Wszystkie mecze Lecha</h2></div><span class="badge text-bg-light">{{ $typerMatches->count() }}</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Mecz</th><th>Data</th><th>Kolejka</th><th>Głosy</th><th></th></tr></thead><tbody>@forelse($typerMatches as $typerMatch)<tr><td>{{ $typerMatch->lech_home ? 'Lech Poznań - '.$typerMatch->opponent : $typerMatch->opponent.' - Lech Poznań' }}<div class="small text-muted-custom">{{ $typerMatch->competition->name }}</div></td><td>{{ $typerMatch->scheduled_at->format('d.m.Y H:i') }}</td><td>{{ $typerMatch->round_number ? 'Kolejka '.$typerMatch->round_number : 'Brak przypisania' }}</td><td>{{ $typerMatch->predictions_count }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.typer.matches.predictions', $typerMatch) }}">Podgląd typów</a></td></tr>@empty<tr><td colspan="5" class="text-muted-custom">Brak meczów w module Typer.</td></tr>@endforelse</tbody></table></div></section>
    </main>
</div></div></div>
</body>
</html>
