<!DOCTYPE html>
<html lang="pl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ config('app.name') }} | Bonusy Typera</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body><div class="admin-shell"><div class="container-fluid"><div class="row min-vh-100">@include('admin.partials.sidebar')<main class="admin-content col-lg-10 p-3 p-md-4 p-xl-5">
<header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><p class="eyebrow mb-2">Typer Lecha</p><h1 class="font-display h3 mb-1">Bonusy Typera</h1><p class="text-muted-custom mb-0">Globalna pula pytań i statystyki ich wykorzystania.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('admin.typer.index') }}">Mecze Typera</a><form method="POST" action="{{ route('logout') }}" class="m-0">@csrf<button class="btn btn-outline-secondary">Wyloguj</button></form></div></header>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="bg-white border rounded-3 p-3 p-md-4 mb-4"><p class="eyebrow mb-2">Globalna pula</p><h2 class="font-display h5 mb-3">Dodaj neutralne pytanie</h2><form method="POST" action="{{ route('admin.bonuses.questions.store') }}" class="row g-3 align-items-end">@csrf<div class="col-md-9"><label class="form-label">Treść pytania</label><input name="question_text" class="form-control" maxlength="500" required></div><div class="col-md-3"><button class="btn btn-primary w-100">Dodaj pytanie</button></div></form></section>
<section class="bg-white border rounded-3 p-3 p-md-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><p class="eyebrow mb-2">Pula pytań</p><h2 class="font-display h5 mb-0">Statystyki pytań</h2></div><span class="badge text-bg-light">{{ $questions->count() }} pytań</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pytanie</th><th>Użycia</th><th>Odpowiedzi</th><th>Poprawne</th></tr></thead><tbody>@forelse($questions as $question)@php $answers = $question->assignments->flatMap->answers; $answered = $answers->filter(fn ($answer) => $answer->answer !== null); $correct = $answered->filter(fn ($answer) => $answer->question?->correct_answer !== null && (bool) $answer->answer === (bool) $answer->question->correct_answer); $percentage = $answered->count() > 0 ? round($correct->count() / $answered->count() * 100, 1) : 0; @endphp<tr><td>{{ $question->question_text }}</td><td>{{ $question->assignments->count() }}</td><td>{{ $answered->count() }}</td><td>{{ $percentage }}%</td></tr>@empty<tr><td colspan="4" class="text-muted-custom">Brak pytań w puli.</td></tr>@endforelse</tbody></table></div></section>
<section class="d-grid gap-4">@forelse($matches as $match)<article id="match-{{ $match->id }}" class="bg-white border rounded-3 p-3 p-md-4"><div class="d-flex justify-content-between gap-3 mb-3"><div><p class="eyebrow mb-2">{{ $match->competition->name }}</p><h2 class="font-display h5 mb-1">{{ $match->lech_home ? 'Lech Poznań - '.$match->opponent : $match->opponent.' - Lech Poznań' }}</h2></div><span class="badge text-bg-light">{{ $match->bonusQuestions->count() }} / 10</span></div><form method="POST" action="{{ route('admin.bonuses.assign', $match) }}">@csrf<div class="row g-3">@foreach(['offensive' => 'Ofensywne', 'defensive' => 'Defensywne'] as $type => $label)<div class="col-lg-6"><h3 class="font-display h6">{{ $label }}</h3>@foreach(range(0, 4) as $slot)@php $selectedId = $match->bonusQuestions->where('type', $type)->values()->get($slot)?->pool_question_id; @endphp<select name="{{ $type }}[]" class="form-select mb-2"><option value="">Wybierz pytanie {{ $slot + 1 }}</option>@foreach($questions as $question)<option value="{{ $question->id }}" @selected($selectedId === $question->id) @disabled($match->bonusQuestions->pluck('pool_question_id')->contains($question->id) && $selectedId !== $question->id)>{{ $question->question_text }}</option>@endforeach</select>@endforeach</div>@endforeach</div><div class="d-flex flex-wrap gap-2 mt-3"><button class="btn btn-outline-primary">Zapisz wybrane</button></form><form method="POST" action="{{ route('admin.bonuses.draw', $match) }}">@csrf<button class="btn btn-primary">Losuj puste miejsca</button></form></div></article>@empty<p class="text-muted-custom">Brak meczów Lecha.</p>@endforelse</section>
</main></div></div></div></body></html>
