<?php

use App\Http\Controllers\AdminLeagueController;
use App\Http\Controllers\AdminLeagueManagementController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\LeagueController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', [LeagueController::class, 'home'])->name('home');
Route::get('/aktualnosci', [LeagueController::class, 'home'])->name('news');
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::get('/login/admin', fn () => redirect()->route('login'));
Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
Route::get('/haslo/przypomnij', [AuthController::class, 'showForgotPassword'])->name('password.request');
Route::post('/haslo/przypomnij', [AuthController::class, 'sendPasswordResetLink'])->name('password.email');
Route::get('/haslo/reset/{token}', [AuthController::class, 'showResetPassword'])->name('password.reset');
Route::post('/haslo/reset', [AuthController::class, 'resetPassword'])->name('password.store');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout')->middleware('auth');
Route::view('/admin', 'admin')->name('admin.dashboard')->middleware(['auth', 'admin']);
Route::get('/liga', [LeagueController::class, 'index'])->name('league.index');
Route::get('/liga/{leagueSlug}', [LeagueController::class, 'show'])->name('league.show');
Route::get('/liga/{leagueSlug}/mecz/{match}', [LeagueController::class, 'match'])->name('league.match');
Route::middleware('auth')->group(function (): void {
    Route::post('/liga/mecze/{match}/typ', [LeagueController::class, 'submitSelection'])->name('league.selection.store');
    Route::post('/admin/liga/mecze/{match}/rozlicz', [AdminLeagueController::class, 'completeMatch'])->name('admin.league.matches.complete')->middleware('admin');
    Route::get('/haslo/zmien', [AuthController::class, 'showChangePassword'])->name('password.change');
    Route::post('/haslo/zmien', [AuthController::class, 'changePassword'])->name('password.update');
    Route::get('/profil', [ProfileController::class, 'show'])->name('profile');
    Route::put('/profil/druzyna', [ProfileController::class, 'updateTeamName'])->name('profile.team.update');
    Route::view('/premium', 'premium')->name('premium');
    Route::post('/admin/uzytkownicy', [AuthController::class, 'createUser'])->name('admin.users.store')->middleware('admin');
    Route::get('/admin/ligi', [AdminLeagueManagementController::class, 'index'])->name('admin.leagues.index')->middleware('admin');
    Route::post('/admin/ligi', [AdminLeagueManagementController::class, 'store'])->name('admin.leagues.store')->middleware('admin');
    Route::put('/admin/ligi/{league}', [AdminLeagueManagementController::class, 'update'])->name('admin.leagues.update')->middleware('admin');
    Route::delete('/admin/ligi/{league}', [AdminLeagueManagementController::class, 'destroy'])->name('admin.leagues.destroy')->middleware('admin');
    Route::post('/admin/ligi/sezony', [AdminLeagueManagementController::class, 'attachToSeason'])->name('admin.leagues.seasons.store')->middleware('admin');
    Route::put('/admin/ligi/sezony/{seasonLeague}', [AdminLeagueManagementController::class, 'updateSeasonLeague'])->name('admin.leagues.seasons.update')->middleware('admin');
    Route::delete('/admin/ligi/sezony/{seasonLeague}', [AdminLeagueManagementController::class, 'detachFromSeason'])->name('admin.leagues.seasons.destroy')->middleware('admin');
    Route::post('/admin/ligi/druzyny', [AdminLeagueManagementController::class, 'addTeamToLeague'])->name('admin.leagues.teams.store')->middleware('admin');
    Route::delete('/admin/ligi/druzyny/{seasonTeam}', [AdminLeagueManagementController::class, 'removeTeamFromLeague'])->name('admin.leagues.teams.destroy')->middleware('admin');
    Route::post('/admin/ligi/nowy-sezon', [AdminLeagueManagementController::class, 'createSeason'])->name('admin.leagues.seasons.create')->middleware('admin');
    Route::post('/admin/ligi/terminarz/generuj', [AdminLeagueManagementController::class, 'generateSchedule'])->name('admin.leagues.schedule.generate')->middleware('admin');
    Route::put('/admin/ligi/kolejki/{round}', [AdminLeagueManagementController::class, 'updateRound'])->name('admin.leagues.rounds.update')->middleware('admin');
    Route::get('/admin/terminarz', [AdminLeagueManagementController::class, 'schedule'])->name('admin.schedule.index')->middleware('admin');
    Route::post('/admin/terminarz/mecze', [AdminLeagueManagementController::class, 'storeRealMatch'])->name('admin.schedule.matches.store')->middleware('admin');
    Route::patch('/admin/terminarz/mecze/{realMatch}/kolejka', [AdminLeagueManagementController::class, 'assignRealMatch'])->name('admin.schedule.matches.round.update')->middleware('admin');
    Route::put('/admin/terminarz/kolejki/{round}', [AdminLeagueManagementController::class, 'updateSeasonRound'])->name('admin.schedule.rounds.update')->middleware('admin');
    Route::put('/admin/uzytkownicy/{user}/nazwa-x', [AuthController::class, 'updateXUsername'])->name('admin.users.x-username.update')->middleware('admin');
    Route::view('/admin/uzytkownicy', 'admin.users.index')->name('admin.users.index')->middleware('admin');
    Route::get('/admin/uzytkownicy/dodaj', fn () => redirect()->route('admin.users.index'))->name('admin.users.create')->middleware('admin');
    Route::view('/statystyki', 'stats')->name('stats')->middleware('premium');
    Route::get('/premium/kup/{days}', [PaymentController::class, 'create'])->name('payment.create');
    Route::post('/admin/uzytkownicy/admin', [AuthController::class, 'createUser'])->name('admin.users.admin.store')->middleware('superadmin');
});
Route::post('/platnosci/przelewy24/notify', [PaymentController::class, 'notify'])->name('payment.notify');
Route::get('/platnosci/przelewy24/powrot', [PaymentController::class, 'return'])->name('payment.return');
