<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name') }} | Typer Lecha</title>@vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body><div class="admin-shell"><div class="container-fluid"><div class="row min-vh-100">@include('admin.partials.sidebar')<main class="admin-content col-lg-10 p-3 p-md-4 p-xl-5">
<header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><p class="eyebrow mb-2">Typer Lecha</p><h1 class="font-display h3 mb-1">Mecze i pytania</h1><p class="text-muted-custom mb-0">Wybierz pytania przy meczu albo uzupełnij puste pozycje losowo.</p></div><form method="POST" action="{{ route('logout') }}" class="m-0">@csrf<button class="btn btn-outline-secondary">Wyloguj</button></form></header>
<div class="mb-4"><a class="btn btn-outline-primary" href="{{ route('admin.bonuses.index') }}">Zarządzaj pulą pytań</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="bg-white border rounded-3 p-3 p-md-4 mb-4"><p class="eyebrow mb-2">Nowy mecz</p><h2 class="font-display h5 mb-3">Dodaj typowanie</h2><form method="POST" action="{{ route('admin.typer.matches.store') }}">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label">Rozgrywki</label><select name="competition_id" class="form-select" required>@foreach($competitions as $competition)<option value="{{ $competition->id }}">{{ $competition->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Rywal</label><input name="opponent" class="form-control" required></div><div class="col-md-2"><label class="form-label">Lech</label><select name="lech_home" class="form-select"><option value="1">Gospodarz</option><option value="0">Gość</option></select></div><div class="col-md-2"><label class="form-label">Kolejka</label><input type="number" min="1" max="99" name="round_number" class="form-control" placeholder="np. 1"></div><div class="col-md-2"><label class="form-label">Data</label><input type="datetime-local" name="scheduled_at" class="form-control" required></div></div><button class="btn btn-primary mt-3">Dodaj mecz</button></form></section>
<section class="d-grid gap-4">@forelse($matches as $match)<article class="bg-white border rounded-3 p-3 p-md-4"><div class="d-flex justify-content-between gap-3 mb-3"><div><p class="eyebrow mb-2">{{ $match->competition->name }}{{ $match->round_number ? ' · Kolejka '.$match->round_number : '' }}</p><h2 class="font-display h5 mb-1">{{ $match->lech_home ? 'Lech Poznań - '.$match->opponent : $match->opponent.' - Lech Poznań' }}</h2><p class="text-muted-custom mb-0">{{ $match->scheduled_at->format('d.m.Y H:i') }}</p></div><div class="text-end"><span class="badge text-bg-light d-block mb-2">{{ $match->bonusQuestions->count() }} / 10 pytań</span><button type="button" class="btn btn-sm btn-outline-secondary mb-2" data-bs-toggle="modal" data-bs-target="#edit-match-{{ $match->id }}">Edytuj mecz</button> <a class="btn btn-sm btn-outline-primary" href="{{ route('admin.typer.matches.predictions', $match) }}">Podgląd typów</a></div></div>
<form method="POST" action="{{ route('admin.bonuses.assign', $match) }}">@csrf<div class="row g-3 mb-3">@foreach(['offensive' => 'Ofensywne', 'defensive' => 'Defensywne'] as $type => $label)<div class="col-lg-6"><h3 class="font-display h6">{{ $label }}</h3>@foreach(range(0, 4) as $slot)@php $selectedId = $match->bonusQuestions->where('type', $type)->values()->get($slot)?->pool_question_id; @endphp<select name="{{ $type }}[]" class="form-select mb-2"><option value="">Wybierz pytanie {{ $slot + 1 }}</option>@foreach($questions as $question)<option value="{{ $question->id }}" @selected($selectedId === $question->id) @disabled($match->bonusQuestions->pluck('pool_question_id')->contains($question->id) && $selectedId !== $question->id)>{{ $question->question_text }}</option>@endforeach</select>@endforeach</div>@endforeach</div><div class="d-flex flex-wrap gap-2"><button class="btn btn-outline-primary">Zapisz wybrane pytania</button></form><form method="POST" action="{{ route('admin.bonuses.draw', $match) }}">@csrf<button class="btn btn-primary">Losuj puste miejsca</button></form></div>
<form method="POST" action="{{ route('admin.typer.matches.result.update', $match) }}" class="mt-4">@csrf @method('PATCH')<div class="row g-3"><div class="col-6 col-md-2"><label class="form-label">Wynik Lecha</label><input name="result_home" type="number" min="0" max="99" class="form-control" value="{{ $match->result_home ?? 0 }}" required></div><div class="col-6 col-md-2"><label class="form-label">Wynik rywala</label><input name="result_away" type="number" min="0" max="99" class="form-control" value="{{ $match->result_away ?? 0 }}" required></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="scheduled" @selected($match->status === 'scheduled')>Zaplanowany</option><option value="completed" @selected($match->status === 'completed')>Zakończony</option><option value="cancelled" @selected($match->status === 'cancelled')>Odwołany</option></select></div></div>@if($match->bonusQuestions->isNotEmpty())<div class="border-top mt-4 pt-3"><p class="eyebrow mb-2">Poprawne odpowiedzi w tym meczu</p><p class="text-muted-custom small mb-3">Ustal odpowiedź na podstawie wydarzeń i statystyk tego konkretnego spotkania.</p><div class="row g-3">@foreach($match->bonusQuestions as $question)<div class="col-lg-6"><label class="form-label small">{{ $question->question_text }} <span class="text-muted-custom">({{ $question->type === 'offensive' ? 'ofensywne' : 'defensywne' }})</span></label><select name="correct_answers[{{ $question->id }}]" class="form-select"><option value="">Brak rozstrzygnięcia</option><option value="1" @selected($question->correct_answer === true)>TAK</option><option value="0" @selected($question->correct_answer === false && $question->correct_answer !== null)>NIE</option></select></div>@endforeach</div></div>@endif<button class="btn btn-outline-secondary mt-3">Zapisz wynik i odpowiedzi</button></form>
<div class="modal fade" id="edit-match-{{ $match->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.typer.matches.update', $match) }}">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Edytuj mecz</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-md-6"><label class="form-label">Rozgrywki</label><select name="competition_id" class="form-select" required>@foreach($competitions as $competition)<option value="{{ $competition->id }}" @selected($match->competition_id === $competition->id)>{{ $competition->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Rywal</label><input name="opponent" class="form-control" value="{{ $match->opponent }}" required></div><div class="col-md-4"><label class="form-label">Lech</label><select name="lech_home" class="form-select"><option value="1" @selected($match->lech_home)>Gospodarz</option><option value="0" @selected(! $match->lech_home)>Gość</option></select></div><div class="col-md-4"><label class="form-label">Kolejka</label><input type="number" min="1" max="99" name="round_number" class="form-control" value="{{ $match->round_number }}"></div><div class="col-md-4"><label class="form-label">Data</label><input type="datetime-local" name="scheduled_at" class="form-control" value="{{ $match->scheduled_at->format('Y-m-d\TH:i') }}" required></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Anuluj</button><button class="btn btn-primary">Zapisz zmiany</button></div></form></div></div></div>
</article>@empty<p class="text-muted-custom">Brak meczów Lecha.</p>@endforelse</section>
</main></div></div></div></body></html>
